# Generated by Django 5.1.2 on 2024-10-14 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedditPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=200, unique=True)),
                ('title', models.TextField()),
                ('body', models.TextField()),
                ('sentiment_score', models.FloatField()),
                ('stock_mentioned', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
